import { publicAsset } from '@/lib/asset-path'

export type TarotCardMeta = {
  id: number
  slug: string
  name: string
  kr: string
  meaning: string
  arcana: 'major' | 'minor'
  suit?: 'wands' | 'cups' | 'swords' | 'pentacles'
  rank?: string
  roman?: string
  filename: string
  image: string
}

export const CARD_BACK_IMAGE = publicAsset('tarot-cards/card-back.webp')

export const TAROT_CARDS: TarotCardMeta[] = [
  {
    id: 0,
    slug: "the-fool",
    name: "The Fool",
    kr: "바보",
    meaning: "fresh start",
    arcana: "major",
    roman: "0",
    filename: "00_major_00_the-fool.webp",
    image: publicAsset("tarot-cards/cards/00_major_00_the-fool.webp"),
  },
  {
    id: 1,
    slug: "the-magician",
    name: "The Magician",
    kr: "마법사",
    meaning: "skill and focus",
    arcana: "major",
    roman: "I",
    filename: "01_major_01_the-magician.webp",
    image: publicAsset("tarot-cards/cards/01_major_01_the-magician.webp"),
  },
  {
    id: 2,
    slug: "the-high-priestess",
    name: "The High Priestess",
    kr: "여사제",
    meaning: "intuition",
    arcana: "major",
    roman: "II",
    filename: "02_major_02_the-high-priestess.webp",
    image: publicAsset("tarot-cards/cards/02_major_02_the-high-priestess.webp"),
  },
  {
    id: 3,
    slug: "the-empress",
    name: "The Empress",
    kr: "여황제",
    meaning: "growth and care",
    arcana: "major",
    roman: "III",
    filename: "03_major_03_the-empress.webp",
    image: publicAsset("tarot-cards/cards/03_major_03_the-empress.webp"),
  },
  {
    id: 4,
    slug: "the-emperor",
    name: "The Emperor",
    kr: "황제",
    meaning: "structure",
    arcana: "major",
    roman: "IV",
    filename: "04_major_04_the-emperor.webp",
    image: publicAsset("tarot-cards/cards/04_major_04_the-emperor.webp"),
  },
  {
    id: 5,
    slug: "the-hierophant",
    name: "The Hierophant",
    kr: "교황",
    meaning: "tradition",
    arcana: "major",
    roman: "V",
    filename: "05_major_05_the-hierophant.webp",
    image: publicAsset("tarot-cards/cards/05_major_05_the-hierophant.webp"),
  },
  {
    id: 6,
    slug: "the-lovers",
    name: "The Lovers",
    kr: "연인",
    meaning: "choice and bond",
    arcana: "major",
    roman: "VI",
    filename: "06_major_06_the-lovers.webp",
    image: publicAsset("tarot-cards/cards/06_major_06_the-lovers.webp"),
  },
  {
    id: 7,
    slug: "the-chariot",
    name: "The Chariot",
    kr: "전차",
    meaning: "willpower",
    arcana: "major",
    roman: "VII",
    filename: "07_major_07_the-chariot.webp",
    image: publicAsset("tarot-cards/cards/07_major_07_the-chariot.webp"),
  },
  {
    id: 8,
    slug: "strength",
    name: "Strength",
    kr: "힘",
    meaning: "gentle courage",
    arcana: "major",
    roman: "VIII",
    filename: "08_major_08_strength.webp",
    image: publicAsset("tarot-cards/cards/08_major_08_strength.webp"),
  },
  {
    id: 9,
    slug: "the-hermit",
    name: "The Hermit",
    kr: "은둔자",
    meaning: "inner light",
    arcana: "major",
    roman: "IX",
    filename: "09_major_09_the-hermit.webp",
    image: publicAsset("tarot-cards/cards/09_major_09_the-hermit.webp"),
  },
  {
    id: 10,
    slug: "wheel-of-fortune",
    name: "Wheel of Fortune",
    kr: "운명의 수레바퀴",
    meaning: "cycles",
    arcana: "major",
    roman: "X",
    filename: "10_major_10_wheel-of-fortune.webp",
    image: publicAsset("tarot-cards/cards/10_major_10_wheel-of-fortune.webp"),
  },
  {
    id: 11,
    slug: "justice",
    name: "Justice",
    kr: "정의",
    meaning: "fairness",
    arcana: "major",
    roman: "XI",
    filename: "11_major_11_justice.webp",
    image: publicAsset("tarot-cards/cards/11_major_11_justice.webp"),
  },
  {
    id: 12,
    slug: "the-hanged-man",
    name: "The Hanged Man",
    kr: "매달린 사람",
    meaning: "new angle",
    arcana: "major",
    roman: "XII",
    filename: "12_major_12_the-hanged-man.webp",
    image: publicAsset("tarot-cards/cards/12_major_12_the-hanged-man.webp"),
  },
  {
    id: 13,
    slug: "death",
    name: "Death",
    kr: "죽음",
    meaning: "transformation",
    arcana: "major",
    roman: "XIII",
    filename: "13_major_13_death.webp",
    image: publicAsset("tarot-cards/cards/13_major_13_death.webp"),
  },
  {
    id: 14,
    slug: "temperance",
    name: "Temperance",
    kr: "절제",
    meaning: "balance",
    arcana: "major",
    roman: "XIV",
    filename: "14_major_14_temperance.webp",
    image: publicAsset("tarot-cards/cards/14_major_14_temperance.webp"),
  },
  {
    id: 15,
    slug: "the-devil",
    name: "The Devil",
    kr: "악마",
    meaning: "attachment",
    arcana: "major",
    roman: "XV",
    filename: "15_major_15_the-devil.webp",
    image: publicAsset("tarot-cards/cards/15_major_15_the-devil.webp"),
  },
  {
    id: 16,
    slug: "the-tower",
    name: "The Tower",
    kr: "탑",
    meaning: "sudden change",
    arcana: "major",
    roman: "XVI",
    filename: "16_major_16_the-tower.webp",
    image: publicAsset("tarot-cards/cards/16_major_16_the-tower.webp"),
  },
  {
    id: 17,
    slug: "the-star",
    name: "The Star",
    kr: "별",
    meaning: "hope",
    arcana: "major",
    roman: "XVII",
    filename: "17_major_17_the-star.webp",
    image: publicAsset("tarot-cards/cards/17_major_17_the-star.webp"),
  },
  {
    id: 18,
    slug: "the-moon",
    name: "The Moon",
    kr: "달",
    meaning: "dreams",
    arcana: "major",
    roman: "XVIII",
    filename: "18_major_18_the-moon.webp",
    image: publicAsset("tarot-cards/cards/18_major_18_the-moon.webp"),
  },
  {
    id: 19,
    slug: "the-sun",
    name: "The Sun",
    kr: "태양",
    meaning: "joy",
    arcana: "major",
    roman: "XIX",
    filename: "19_major_19_the-sun.webp",
    image: publicAsset("tarot-cards/cards/19_major_19_the-sun.webp"),
  },
  {
    id: 20,
    slug: "judgement",
    name: "Judgement",
    kr: "심판",
    meaning: "awakening",
    arcana: "major",
    roman: "XX",
    filename: "20_major_20_judgement.webp",
    image: publicAsset("tarot-cards/cards/20_major_20_judgement.webp"),
  },
  {
    id: 21,
    slug: "the-world",
    name: "The World",
    kr: "세계",
    meaning: "completion",
    arcana: "major",
    roman: "XXI",
    filename: "21_major_21_the-world.webp",
    image: publicAsset("tarot-cards/cards/21_major_21_the-world.webp"),
  },
  {
    id: 22,
    slug: "ace-of-wands",
    name: "Ace of Wands",
    kr: "완드 에이스",
    meaning: "",
    arcana: "minor",
    suit: "wands",
    rank: "Ace",
    filename: "22_wands_ace.webp",
    image: publicAsset("tarot-cards/cards/22_wands_ace.webp"),
  },
  {
    id: 23,
    slug: "two-of-wands",
    name: "Two of Wands",
    kr: "완드 2",
    meaning: "",
    arcana: "minor",
    suit: "wands",
    rank: "Two",
    filename: "23_wands_two.webp",
    image: publicAsset("tarot-cards/cards/23_wands_two.webp"),
  },
  {
    id: 24,
    slug: "three-of-wands",
    name: "Three of Wands",
    kr: "완드 3",
    meaning: "",
    arcana: "minor",
    suit: "wands",
    rank: "Three",
    filename: "24_wands_three.webp",
    image: publicAsset("tarot-cards/cards/24_wands_three.webp"),
  },
  {
    id: 25,
    slug: "four-of-wands",
    name: "Four of Wands",
    kr: "완드 4",
    meaning: "",
    arcana: "minor",
    suit: "wands",
    rank: "Four",
    filename: "25_wands_four.webp",
    image: publicAsset("tarot-cards/cards/25_wands_four.webp"),
  },
  {
    id: 26,
    slug: "five-of-wands",
    name: "Five of Wands",
    kr: "완드 5",
    meaning: "",
    arcana: "minor",
    suit: "wands",
    rank: "Five",
    filename: "26_wands_five.webp",
    image: publicAsset("tarot-cards/cards/26_wands_five.webp"),
  },
  {
    id: 27,
    slug: "six-of-wands",
    name: "Six of Wands",
    kr: "완드 6",
    meaning: "",
    arcana: "minor",
    suit: "wands",
    rank: "Six",
    filename: "27_wands_six.webp",
    image: publicAsset("tarot-cards/cards/27_wands_six.webp"),
  },
  {
    id: 28,
    slug: "seven-of-wands",
    name: "Seven of Wands",
    kr: "완드 7",
    meaning: "",
    arcana: "minor",
    suit: "wands",
    rank: "Seven",
    filename: "28_wands_seven.webp",
    image: publicAsset("tarot-cards/cards/28_wands_seven.webp"),
  },
  {
    id: 29,
    slug: "eight-of-wands",
    name: "Eight of Wands",
    kr: "완드 8",
    meaning: "",
    arcana: "minor",
    suit: "wands",
    rank: "Eight",
    filename: "29_wands_eight.webp",
    image: publicAsset("tarot-cards/cards/29_wands_eight.webp"),
  },
  {
    id: 30,
    slug: "nine-of-wands",
    name: "Nine of Wands",
    kr: "완드 9",
    meaning: "",
    arcana: "minor",
    suit: "wands",
    rank: "Nine",
    filename: "30_wands_nine.webp",
    image: publicAsset("tarot-cards/cards/30_wands_nine.webp"),
  },
  {
    id: 31,
    slug: "ten-of-wands",
    name: "Ten of Wands",
    kr: "완드 10",
    meaning: "",
    arcana: "minor",
    suit: "wands",
    rank: "Ten",
    filename: "31_wands_ten.webp",
    image: publicAsset("tarot-cards/cards/31_wands_ten.webp"),
  },
  {
    id: 32,
    slug: "page-of-wands",
    name: "Page of Wands",
    kr: "완드 시종",
    meaning: "",
    arcana: "minor",
    suit: "wands",
    rank: "Page",
    filename: "32_wands_page.webp",
    image: publicAsset("tarot-cards/cards/32_wands_page.webp"),
  },
  {
    id: 33,
    slug: "knight-of-wands",
    name: "Knight of Wands",
    kr: "완드 기사",
    meaning: "",
    arcana: "minor",
    suit: "wands",
    rank: "Knight",
    filename: "33_wands_knight.webp",
    image: publicAsset("tarot-cards/cards/33_wands_knight.webp"),
  },
  {
    id: 34,
    slug: "queen-of-wands",
    name: "Queen of Wands",
    kr: "완드 여왕",
    meaning: "",
    arcana: "minor",
    suit: "wands",
    rank: "Queen",
    filename: "34_wands_queen.webp",
    image: publicAsset("tarot-cards/cards/34_wands_queen.webp"),
  },
  {
    id: 35,
    slug: "king-of-wands",
    name: "King of Wands",
    kr: "완드 왕",
    meaning: "",
    arcana: "minor",
    suit: "wands",
    rank: "King",
    filename: "35_wands_king.webp",
    image: publicAsset("tarot-cards/cards/35_wands_king.webp"),
  },
  {
    id: 36,
    slug: "ace-of-cups",
    name: "Ace of Cups",
    kr: "컵 에이스",
    meaning: "",
    arcana: "minor",
    suit: "cups",
    rank: "Ace",
    filename: "36_cups_ace.webp",
    image: publicAsset("tarot-cards/cards/36_cups_ace.webp"),
  },
  {
    id: 37,
    slug: "two-of-cups",
    name: "Two of Cups",
    kr: "컵 2",
    meaning: "",
    arcana: "minor",
    suit: "cups",
    rank: "Two",
    filename: "37_cups_two.webp",
    image: publicAsset("tarot-cards/cards/37_cups_two.webp"),
  },
  {
    id: 38,
    slug: "three-of-cups",
    name: "Three of Cups",
    kr: "컵 3",
    meaning: "",
    arcana: "minor",
    suit: "cups",
    rank: "Three",
    filename: "38_cups_three.webp",
    image: publicAsset("tarot-cards/cards/38_cups_three.webp"),
  },
  {
    id: 39,
    slug: "four-of-cups",
    name: "Four of Cups",
    kr: "컵 4",
    meaning: "",
    arcana: "minor",
    suit: "cups",
    rank: "Four",
    filename: "39_cups_four.webp",
    image: publicAsset("tarot-cards/cards/39_cups_four.webp"),
  },
  {
    id: 40,
    slug: "five-of-cups",
    name: "Five of Cups",
    kr: "컵 5",
    meaning: "",
    arcana: "minor",
    suit: "cups",
    rank: "Five",
    filename: "40_cups_five.webp",
    image: publicAsset("tarot-cards/cards/40_cups_five.webp"),
  },
  {
    id: 41,
    slug: "six-of-cups",
    name: "Six of Cups",
    kr: "컵 6",
    meaning: "",
    arcana: "minor",
    suit: "cups",
    rank: "Six",
    filename: "41_cups_six.webp",
    image: publicAsset("tarot-cards/cards/41_cups_six.webp"),
  },
  {
    id: 42,
    slug: "seven-of-cups",
    name: "Seven of Cups",
    kr: "컵 7",
    meaning: "",
    arcana: "minor",
    suit: "cups",
    rank: "Seven",
    filename: "42_cups_seven.webp",
    image: publicAsset("tarot-cards/cards/42_cups_seven.webp"),
  },
  {
    id: 43,
    slug: "eight-of-cups",
    name: "Eight of Cups",
    kr: "컵 8",
    meaning: "",
    arcana: "minor",
    suit: "cups",
    rank: "Eight",
    filename: "43_cups_eight.webp",
    image: publicAsset("tarot-cards/cards/43_cups_eight.webp"),
  },
  {
    id: 44,
    slug: "nine-of-cups",
    name: "Nine of Cups",
    kr: "컵 9",
    meaning: "",
    arcana: "minor",
    suit: "cups",
    rank: "Nine",
    filename: "44_cups_nine.webp",
    image: publicAsset("tarot-cards/cards/44_cups_nine.webp"),
  },
  {
    id: 45,
    slug: "ten-of-cups",
    name: "Ten of Cups",
    kr: "컵 10",
    meaning: "",
    arcana: "minor",
    suit: "cups",
    rank: "Ten",
    filename: "45_cups_ten.webp",
    image: publicAsset("tarot-cards/cards/45_cups_ten.webp"),
  },
  {
    id: 46,
    slug: "page-of-cups",
    name: "Page of Cups",
    kr: "컵 시종",
    meaning: "",
    arcana: "minor",
    suit: "cups",
    rank: "Page",
    filename: "46_cups_page.webp",
    image: publicAsset("tarot-cards/cards/46_cups_page.webp"),
  },
  {
    id: 47,
    slug: "knight-of-cups",
    name: "Knight of Cups",
    kr: "컵 기사",
    meaning: "",
    arcana: "minor",
    suit: "cups",
    rank: "Knight",
    filename: "47_cups_knight.webp",
    image: publicAsset("tarot-cards/cards/47_cups_knight.webp"),
  },
  {
    id: 48,
    slug: "queen-of-cups",
    name: "Queen of Cups",
    kr: "컵 여왕",
    meaning: "",
    arcana: "minor",
    suit: "cups",
    rank: "Queen",
    filename: "48_cups_queen.webp",
    image: publicAsset("tarot-cards/cards/48_cups_queen.webp"),
  },
  {
    id: 49,
    slug: "king-of-cups",
    name: "King of Cups",
    kr: "컵 왕",
    meaning: "",
    arcana: "minor",
    suit: "cups",
    rank: "King",
    filename: "49_cups_king.webp",
    image: publicAsset("tarot-cards/cards/49_cups_king.webp"),
  },
  {
    id: 50,
    slug: "ace-of-swords",
    name: "Ace of Swords",
    kr: "소드 에이스",
    meaning: "",
    arcana: "minor",
    suit: "swords",
    rank: "Ace",
    filename: "50_swords_ace.webp",
    image: publicAsset("tarot-cards/cards/50_swords_ace.webp"),
  },
  {
    id: 51,
    slug: "two-of-swords",
    name: "Two of Swords",
    kr: "소드 2",
    meaning: "",
    arcana: "minor",
    suit: "swords",
    rank: "Two",
    filename: "51_swords_two.webp",
    image: publicAsset("tarot-cards/cards/51_swords_two.webp"),
  },
  {
    id: 52,
    slug: "three-of-swords",
    name: "Three of Swords",
    kr: "소드 3",
    meaning: "",
    arcana: "minor",
    suit: "swords",
    rank: "Three",
    filename: "52_swords_three.webp",
    image: publicAsset("tarot-cards/cards/52_swords_three.webp"),
  },
  {
    id: 53,
    slug: "four-of-swords",
    name: "Four of Swords",
    kr: "소드 4",
    meaning: "",
    arcana: "minor",
    suit: "swords",
    rank: "Four",
    filename: "53_swords_four.webp",
    image: publicAsset("tarot-cards/cards/53_swords_four.webp"),
  },
  {
    id: 54,
    slug: "five-of-swords",
    name: "Five of Swords",
    kr: "소드 5",
    meaning: "",
    arcana: "minor",
    suit: "swords",
    rank: "Five",
    filename: "54_swords_five.webp",
    image: publicAsset("tarot-cards/cards/54_swords_five.webp"),
  },
  {
    id: 55,
    slug: "six-of-swords",
    name: "Six of Swords",
    kr: "소드 6",
    meaning: "",
    arcana: "minor",
    suit: "swords",
    rank: "Six",
    filename: "55_swords_six.webp",
    image: publicAsset("tarot-cards/cards/55_swords_six.webp"),
  },
  {
    id: 56,
    slug: "seven-of-swords",
    name: "Seven of Swords",
    kr: "소드 7",
    meaning: "",
    arcana: "minor",
    suit: "swords",
    rank: "Seven",
    filename: "56_swords_seven.webp",
    image: publicAsset("tarot-cards/cards/56_swords_seven.webp"),
  },
  {
    id: 57,
    slug: "eight-of-swords",
    name: "Eight of Swords",
    kr: "소드 8",
    meaning: "",
    arcana: "minor",
    suit: "swords",
    rank: "Eight",
    filename: "57_swords_eight.webp",
    image: publicAsset("tarot-cards/cards/57_swords_eight.webp"),
  },
  {
    id: 58,
    slug: "nine-of-swords",
    name: "Nine of Swords",
    kr: "소드 9",
    meaning: "",
    arcana: "minor",
    suit: "swords",
    rank: "Nine",
    filename: "58_swords_nine.webp",
    image: publicAsset("tarot-cards/cards/58_swords_nine.webp"),
  },
  {
    id: 59,
    slug: "ten-of-swords",
    name: "Ten of Swords",
    kr: "소드 10",
    meaning: "",
    arcana: "minor",
    suit: "swords",
    rank: "Ten",
    filename: "59_swords_ten.webp",
    image: publicAsset("tarot-cards/cards/59_swords_ten.webp"),
  },
  {
    id: 60,
    slug: "page-of-swords",
    name: "Page of Swords",
    kr: "소드 시종",
    meaning: "",
    arcana: "minor",
    suit: "swords",
    rank: "Page",
    filename: "60_swords_page.webp",
    image: publicAsset("tarot-cards/cards/60_swords_page.webp"),
  },
  {
    id: 61,
    slug: "knight-of-swords",
    name: "Knight of Swords",
    kr: "소드 기사",
    meaning: "",
    arcana: "minor",
    suit: "swords",
    rank: "Knight",
    filename: "61_swords_knight.webp",
    image: publicAsset("tarot-cards/cards/61_swords_knight.webp"),
  },
  {
    id: 62,
    slug: "queen-of-swords",
    name: "Queen of Swords",
    kr: "소드 여왕",
    meaning: "",
    arcana: "minor",
    suit: "swords",
    rank: "Queen",
    filename: "62_swords_queen.webp",
    image: publicAsset("tarot-cards/cards/62_swords_queen.webp"),
  },
  {
    id: 63,
    slug: "king-of-swords",
    name: "King of Swords",
    kr: "소드 왕",
    meaning: "",
    arcana: "minor",
    suit: "swords",
    rank: "King",
    filename: "63_swords_king.webp",
    image: publicAsset("tarot-cards/cards/63_swords_king.webp"),
  },
  {
    id: 64,
    slug: "ace-of-pentacles",
    name: "Ace of Pentacles",
    kr: "파이 코인 에이스",
    meaning: "",
    arcana: "minor",
    suit: "pentacles",
    rank: "Ace",
    filename: "64_pentacles_ace.webp",
    image: publicAsset("tarot-cards/cards/64_pentacles_ace.webp"),
  },
  {
    id: 65,
    slug: "two-of-pentacles",
    name: "Two of Pentacles",
    kr: "파이 코인 2",
    meaning: "",
    arcana: "minor",
    suit: "pentacles",
    rank: "Two",
    filename: "65_pentacles_two.webp",
    image: publicAsset("tarot-cards/cards/65_pentacles_two.webp"),
  },
  {
    id: 66,
    slug: "three-of-pentacles",
    name: "Three of Pentacles",
    kr: "파이 코인 3",
    meaning: "",
    arcana: "minor",
    suit: "pentacles",
    rank: "Three",
    filename: "66_pentacles_three.webp",
    image: publicAsset("tarot-cards/cards/66_pentacles_three.webp"),
  },
  {
    id: 67,
    slug: "four-of-pentacles",
    name: "Four of Pentacles",
    kr: "파이 코인 4",
    meaning: "",
    arcana: "minor",
    suit: "pentacles",
    rank: "Four",
    filename: "67_pentacles_four.webp",
    image: publicAsset("tarot-cards/cards/67_pentacles_four.webp"),
  },
  {
    id: 68,
    slug: "five-of-pentacles",
    name: "Five of Pentacles",
    kr: "파이 코인 5",
    meaning: "",
    arcana: "minor",
    suit: "pentacles",
    rank: "Five",
    filename: "68_pentacles_five.webp",
    image: publicAsset("tarot-cards/cards/68_pentacles_five.webp"),
  },
  {
    id: 69,
    slug: "six-of-pentacles",
    name: "Six of Pentacles",
    kr: "파이 코인 6",
    meaning: "",
    arcana: "minor",
    suit: "pentacles",
    rank: "Six",
    filename: "69_pentacles_six.webp",
    image: publicAsset("tarot-cards/cards/69_pentacles_six.webp"),
  },
  {
    id: 70,
    slug: "seven-of-pentacles",
    name: "Seven of Pentacles",
    kr: "파이 코인 7",
    meaning: "",
    arcana: "minor",
    suit: "pentacles",
    rank: "Seven",
    filename: "70_pentacles_seven.webp",
    image: publicAsset("tarot-cards/cards/70_pentacles_seven.webp"),
  },
  {
    id: 71,
    slug: "eight-of-pentacles",
    name: "Eight of Pentacles",
    kr: "파이 코인 8",
    meaning: "",
    arcana: "minor",
    suit: "pentacles",
    rank: "Eight",
    filename: "71_pentacles_eight.webp",
    image: publicAsset("tarot-cards/cards/71_pentacles_eight.webp"),
  },
  {
    id: 72,
    slug: "nine-of-pentacles",
    name: "Nine of Pentacles",
    kr: "파이 코인 9",
    meaning: "",
    arcana: "minor",
    suit: "pentacles",
    rank: "Nine",
    filename: "72_pentacles_nine.webp",
    image: publicAsset("tarot-cards/cards/72_pentacles_nine.webp"),
  },
  {
    id: 73,
    slug: "ten-of-pentacles",
    name: "Ten of Pentacles",
    kr: "파이 코인 10",
    meaning: "",
    arcana: "minor",
    suit: "pentacles",
    rank: "Ten",
    filename: "73_pentacles_ten.webp",
    image: publicAsset("tarot-cards/cards/73_pentacles_ten.webp"),
  },
  {
    id: 74,
    slug: "page-of-pentacles",
    name: "Page of Pentacles",
    kr: "파이 코인 시종",
    meaning: "",
    arcana: "minor",
    suit: "pentacles",
    rank: "Page",
    filename: "74_pentacles_page.webp",
    image: publicAsset("tarot-cards/cards/74_pentacles_page.webp"),
  },
  {
    id: 75,
    slug: "knight-of-pentacles",
    name: "Knight of Pentacles",
    kr: "파이 코인 기사",
    meaning: "",
    arcana: "minor",
    suit: "pentacles",
    rank: "Knight",
    filename: "75_pentacles_knight.webp",
    image: publicAsset("tarot-cards/cards/75_pentacles_knight.webp"),
  },
  {
    id: 76,
    slug: "queen-of-pentacles",
    name: "Queen of Pentacles",
    kr: "파이 코인 여왕",
    meaning: "",
    arcana: "minor",
    suit: "pentacles",
    rank: "Queen",
    filename: "76_pentacles_queen.webp",
    image: publicAsset("tarot-cards/cards/76_pentacles_queen.webp"),
  },
  {
    id: 77,
    slug: "king-of-pentacles",
    name: "King of Pentacles",
    kr: "파이 코인 왕",
    meaning: "",
    arcana: "minor",
    suit: "pentacles",
    rank: "King",
    filename: "77_pentacles_king.webp",
    image: publicAsset("tarot-cards/cards/77_pentacles_king.webp"),
  },
]

export const TOTAL_CARDS = TAROT_CARDS.length

export function getTarotCard(id: number) {
  return TAROT_CARDS.find((card) => card.id === id)
}

export function getCardLabel(id: number) {
  const card = getTarotCard(id)
  return card ? `${card.name} · ${card.kr}` : `Card ${id}`
}
